### ISSUE TITLE
Does it work for Fermi?

### ISSUE THREAD

**Issue by leimingyu** [NVlabs/SASSI#1] opened 2015-08-13 16:53 UTC
Hello,
    In the paper, it says SASSI works for Fermi. But compiling only supports device with capability >= 3.0. Fermi architecture is 2.0+. It will fail during compilation stage when building examples.
    How to make SASSI work for Fermi?

Best,
Leiming

**Comment by mwstephenson** [comment] 2015-08-13 18:51
Hi Leiming,
Good question.  SASSI will work for Fermi, but many (most?) of the sample instrumentation libraries we have provided use some convenient features that are only supported in 3.0+ architectures.  Let me take a quick look and see which of those sample libraries will work on Fermi and add a target to the makefile to only build those.

Thanks,
Mark

**Comment by mwstephenson** [comment] 2015-08-13 19:58
First, I confess that we haven't been focused on Fermi for quite a while.  Most of us internally use Kepler devices, and I have been using Maxwell.  That said, one of the benefits of being cooked into the compiler backend is that the instrumentation portion of SASSI should just work.  However, it looks like all of the sample instrumentation libraries except one use UVM `__managed__` data structures to remove the pain of explicitly copying data back and forth between the host and device.  In addition, some of the libraries use some warp-collective operations that only work on 3.0+ architectures.  

There is one sample instrumentation library that works on Fermi, but you will not think it is very interesting.  It is essentially a stubbed-out handler, called "stubs" that I use for debugging.  I just verified that my regression tests pass for "stubs" on Fermi.  I will back-port a simple example, such as ophist, to Fermi and push out a change when that's done.

**Comment by leimingyu** [comment] 2015-08-14 00:39
Thanks, Mark.

**Comment by mwstephenson** [comment] 2015-08-21 15:39
Sorry this took so long.  I back-ported the `ophist` example so that it will work with Fermi.  In the process, I discovered a bug that could affect the perceived register allocation (and therefore warp occupancy) and instruction schedule of application.  On Fermi this bug caused the example application, matrixMul, to outright fail.  You will need to grab a new installer and reinstall SASSI to get the bugfix.  I'm closing this issue for now.

**Closed as completed by mwstephenson** 2015-08-21 15:39 UTC
